In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
randint = torch.randint(-100, 100, (6,)) #takes 6 random numbers in between -100 and 100 
randint

tensor([-64, -15,  29, -54, -88, -88])

In [3]:
tensor = torch.tensor([[0.2, 1.2], [4,3.55], [56.7, 44]]) #takes intigers and writes them as a 2*n tensor 
tensor

tensor([[ 0.2000,  1.2000],
        [ 4.0000,  3.5500],
        [56.7000, 44.0000]])

In [4]:
zeros = torch.zeros(2, 4) #takes dimensions and writes them with zeros 
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
ones = torch.ones(5, 2) #the same as zeros but with ones
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
input = torch.empty(2, 2)           #fills the set dimentions with random large or small numbers
input

tensor([[0., 0.],
        [0., 0.]])

In [7]:
arange = torch.arange(6) #aranges input from 0 to n 
arange

tensor([0, 1, 2, 3, 4, 5])

In [8]:
linspace = torch.linspace(3, 10, steps=5) #makes n of steps from 3 to 10
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
eye = torch.eye(4) #makes a diagnal line of the matrix n
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [10]:
probabilities = torch.tensor([0.1, 0.9]) #make a tensor to use that has to addup to 1 cause 1=100%, 0,1=10%, 0,9=90%
samples = torch.multinomial(probabilities, num_samples = 10, replacement=True) #takes the tensor and run 10 diffrent chances 
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [11]:
tensor_cat = torch.tensor([1, 2, 3])
cat = torch.cat((tensor_cat, torch.tensor([4])), dim=0) #combines two tensors (the second one must have only 1 parameter)
print(cat)

tensor([1, 2, 3, 4])


In [12]:
trill = torch.tril(torch.ones(5, 5)) #trill = triangle lower, creates a triangle of ones on the lower half
trill

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [13]:
triu = torch.triu(torch.ones(5, 5)) #triu = triangle upper, creates a triangle of ones on the upper half
triu

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [14]:
out = torch.zeros(5, 5,).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf')) # Creates a lower-triangular matrix with 0s and fills the upper triangle with -inf for masking 
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [15]:
tensor_trans = torch.zeros(2, 3, 4)
trans = tensor_trans.transpose(0, 2) #flips the zeroes position wiht the second 
trans.shape

torch.Size([4, 3, 2])

In [16]:
tensor1 = torch.tensor([1 ,2, 3])
tensor2 = torch.tensor([4 ,5, 6])
tensor3 = torch.tensor([7 ,8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3]) #stacks tensors on top of each other 
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.,])
linear = nn.Linear(3, 3, bias=False) # Applies a linear transformation (no bias) to the input [10, 10, 10] using a randomly initialized 3x3 weight matrix
print(linear(sample))

tensor([ 0.6864, -6.3564,  5.3898], grad_fn=<SqueezeBackward4>)


In [18]:
import torch.nn.functional as F
fun_tensor = torch.tensor([1., 2., 3.,])
softmax_output = F.softmax(fun_tensor, dim=0) #exponenties the tensor (2.71^n) and the sums the outputs and then devides the exp. numbers but the sum
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [19]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b) #@ is used for multiplication matrixes 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [22]:
embedding = nn.Embedding(5, 3)
ids = torch.tensor([0, 3])
print(embedding(ids))

tensor([[-1.3154, -0.6026, -0.4345],
        [-0.4331,  1.7591,  0.0220]], grad_fn=<EmbeddingBackward0>)


In [27]:

logits = torch.tensor([[2.0, 0.5, 0.3]])  # prediction for one example
target = torch.tensor([0])  # correct answer is class 0
loss = F.cross_entropy(logits, target)
print(loss)  # smaller if prediction is closer to target


tensor(0.3406)


In [28]:
x = torch.tensor([-0.06], dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4850])
